const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "2348101119500,2348158553029";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "2347056025320";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",

  sessionName:process.env.SESSION_ID || "SUHAIL_16_45_10_06_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTEyLFxuICAgICAgICAyMTksXG4gICAgICAgIDEyOCxcbiAgICAgICAgMTMxLFxuICAgICAgICAyMzgsXG4gICAgICAgIDIxNSxcbiAgICAgICAgMjUxLFxuICAgICAgICAyMjksXG4gICAgICAgIDIyNyxcbiAgICAgICAgMTA5LFxuICAgICAgICAxMDUsXG4gICAgICAgIDIzLFxuICAgICAgICAxNTMsXG4gICAgICAgIDI1LFxuICAgICAgICAxMTQsXG4gICAgICAgIDEwNCxcbiAgICAgICAgMjM0LFxuICAgICAgICAxMTQsXG4gICAgICAgIDkzLFxuICAgICAgICAxNjUsXG4gICAgICAgIDIyLFxuICAgICAgICAyMzcsXG4gICAgICAgIDIzMCxcbiAgICAgICAgMTcyLFxuICAgICAgICA3OCxcbiAgICAgICAgMTY3LFxuICAgICAgICAxMzcsXG4gICAgICAgIDExMixcbiAgICAgICAgNDcsXG4gICAgICAgIDE1MSxcbiAgICAgICAgMTUxLFxuICAgICAgICAxMjVcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMzYsXG4gICAgICAgIDE1MSxcbiAgICAgICAgMTQwLFxuICAgICAgICAxMjMsXG4gICAgICAgIDk0LFxuICAgICAgICAxMyxcbiAgICAgICAgMTU0LFxuICAgICAgICAxMjgsXG4gICAgICAgIDI0OSxcbiAgICAgICAgMjAzLFxuICAgICAgICAxMjcsXG4gICAgICAgIDE0OSxcbiAgICAgICAgMTYyLFxuICAgICAgICA0OSxcbiAgICAgICAgMTY0LFxuICAgICAgICAxNzYsXG4gICAgICAgIDExOSxcbiAgICAgICAgMjE5LFxuICAgICAgICAxNTAsXG4gICAgICAgIDE4OCxcbiAgICAgICAgOTUsXG4gICAgICAgIDEzNSxcbiAgICAgICAgMjIsXG4gICAgICAgIDAsXG4gICAgICAgIDM5LFxuICAgICAgICA2LFxuICAgICAgICAxNDEsXG4gICAgICAgIDE0LFxuICAgICAgICAyNDIsXG4gICAgICAgIDIxLFxuICAgICAgICAxNTUsXG4gICAgICAgIDY4XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyXCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA4OCxcbiAgICAgICAgNzcsXG4gICAgICAgIDc2LFxuICAgICAgICAyNDksXG4gICAgICAgIDIwNCxcbiAgICAgICAgMjgsXG4gICAgICAgIDI0NCxcbiAgICAgICAgMjMyLFxuICAgICAgICAyMzUsXG4gICAgICAgIDIxNyxcbiAgICAgICAgMTU1LFxuICAgICAgICA4NixcbiAgICAgICAgMTYsXG4gICAgICAgIDIwNixcbiAgICAgICAgMTk0LFxuICAgICAgICAyNSxcbiAgICAgICAgMTI5LFxuICAgICAgICAzNixcbiAgICAgICAgMTA1LFxuICAgICAgICAxOTQsXG4gICAgICAgIDIyMSxcbiAgICAgICAgMTEzLFxuICAgICAgICAxMjYsXG4gICAgICAgIDE1MSxcbiAgICAgICAgNTMsXG4gICAgICAgIDQ2LFxuICAgICAgICAzNCxcbiAgICAgICAgMTI1LFxuICAgICAgICAxMTAsXG4gICAgICAgIDIwMCxcbiAgICAgICAgMjI3LFxuICAgICAgICAxMTlcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjE2LFxuICAgICAgICA3MixcbiAgICAgICAgMjEyLFxuICAgICAgICAxMixcbiAgICAgICAgMjEzLFxuICAgICAgICAyNTAsXG4gICAgICAgIDI0NCxcbiAgICAgICAgMTc0LFxuICAgICAgICAxNzMsXG4gICAgICAgIDIyNCxcbiAgICAgICAgNzAsXG4gICAgICAgIDE2NCxcbiAgICAgICAgMTA4LFxuICAgICAgICAxNjgsXG4gICAgICAgIDMwLFxuICAgICAgICAyLFxuICAgICAgICA0NyxcbiAgICAgICAgNzksXG4gICAgICAgIDExOCxcbiAgICAgICAgMTE1LFxuICAgICAgICAxMSxcbiAgICAgICAgMjIwLFxuICAgICAgICAxMzAsXG4gICAgICAgIDE4MixcbiAgICAgICAgMTE5LFxuICAgICAgICAzMyxcbiAgICAgICAgMjIsXG4gICAgICAgIDI3LFxuICAgICAgICAyNTMsXG4gICAgICAgIDMsXG4gICAgICAgIDc2LFxuICAgICAgICAxMDBcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkSWRlbnRpdHlLZXlcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDI0MCxcbiAgICAgICAgMTg4LFxuICAgICAgICAxNDMsXG4gICAgICAgIDcsXG4gICAgICAgIDI0NCxcbiAgICAgICAgMjMsXG4gICAgICAgIDI1MCxcbiAgICAgICAgMTUxLFxuICAgICAgICAyNTAsXG4gICAgICAgIDE3OCxcbiAgICAgICAgMTQzLFxuICAgICAgICA3MixcbiAgICAgICAgMjUzLFxuICAgICAgICA1NixcbiAgICAgICAgMjE2LFxuICAgICAgICA4OSxcbiAgICAgICAgNzEsXG4gICAgICAgIDc1LFxuICAgICAgICAxLFxuICAgICAgICA4LFxuICAgICAgICAyMjksXG4gICAgICAgIDIzMixcbiAgICAgICAgMTIzLFxuICAgICAgICAxMzAsXG4gICAgICAgIDIxLFxuICAgICAgICAxMDYsXG4gICAgICAgIDEyMyxcbiAgICAgICAgMzYsXG4gICAgICAgIDE3MyxcbiAgICAgICAgMTQ1LFxuICAgICAgICA1OSxcbiAgICAgICAgODVcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTE1LFxuICAgICAgICA0OCxcbiAgICAgICAgNSxcbiAgICAgICAgMjExLFxuICAgICAgICA3MyxcbiAgICAgICAgNjgsXG4gICAgICAgIDE4OSxcbiAgICAgICAgMjM0LFxuICAgICAgICA1NSxcbiAgICAgICAgMTg1LFxuICAgICAgICAxNzMsXG4gICAgICAgIDE4NCxcbiAgICAgICAgMjUzLFxuICAgICAgICAxNDAsXG4gICAgICAgIDU5LFxuICAgICAgICAyMTUsXG4gICAgICAgIDY3LFxuICAgICAgICAxMDMsXG4gICAgICAgIDg1LFxuICAgICAgICAxMjgsXG4gICAgICAgIDYyLFxuICAgICAgICAyMSxcbiAgICAgICAgMTk1LFxuICAgICAgICA5MixcbiAgICAgICAgMTI3LFxuICAgICAgICAyMzMsXG4gICAgICAgIDI0OCxcbiAgICAgICAgNjAsXG4gICAgICAgIDk2LFxuICAgICAgICA0MixcbiAgICAgICAgMTI4LFxuICAgICAgICAyXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZFByZUtleVwiOiB7XG4gICAgXCJrZXlQYWlyXCI6IHtcbiAgICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDIxNixcbiAgICAgICAgICA3NixcbiAgICAgICAgICAyMzAsXG4gICAgICAgICAgMTYsXG4gICAgICAgICAgMTQwLFxuICAgICAgICAgIDEwOCxcbiAgICAgICAgICA1OCxcbiAgICAgICAgICAxMTAsXG4gICAgICAgICAgMTM0LFxuICAgICAgICAgIDUyLFxuICAgICAgICAgIDg2LFxuICAgICAgICAgIDI0OCxcbiAgICAgICAgICAxNzIsXG4gICAgICAgICAgMTM4LFxuICAgICAgICAgIDEyOSxcbiAgICAgICAgICAxNzUsXG4gICAgICAgICAgMjMsXG4gICAgICAgICAgNTAsXG4gICAgICAgICAgMTkxLFxuICAgICAgICAgIDIzMixcbiAgICAgICAgICA4NCxcbiAgICAgICAgICAyMjcsXG4gICAgICAgICAgODUsXG4gICAgICAgICAgNDcsXG4gICAgICAgICAgMTc5LFxuICAgICAgICAgIDI0MixcbiAgICAgICAgICAyMDUsXG4gICAgICAgICAgNjEsXG4gICAgICAgICAgODgsXG4gICAgICAgICAgMTgyLFxuICAgICAgICAgIDg0LFxuICAgICAgICAgIDExMlxuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAyMTUsXG4gICAgICAgICAgMzMsXG4gICAgICAgICAgNDUsXG4gICAgICAgICAgMTI1LFxuICAgICAgICAgIDE0MixcbiAgICAgICAgICAyMzMsXG4gICAgICAgICAgOCxcbiAgICAgICAgICA3NixcbiAgICAgICAgICAyMDIsXG4gICAgICAgICAgMjUwLFxuICAgICAgICAgIDIwMCxcbiAgICAgICAgICA5NixcbiAgICAgICAgICAxMzksXG4gICAgICAgICAgMTUxLFxuICAgICAgICAgIDg0LFxuICAgICAgICAgIDEyOCxcbiAgICAgICAgICAyMDksXG4gICAgICAgICAgMTE1LFxuICAgICAgICAgIDUzLFxuICAgICAgICAgIDE4NCxcbiAgICAgICAgICAxMjIsXG4gICAgICAgICAgMTUsXG4gICAgICAgICAgMTkyLFxuICAgICAgICAgIDcxLFxuICAgICAgICAgIDI0NixcbiAgICAgICAgICAxMTIsXG4gICAgICAgICAgNzEsXG4gICAgICAgICAgMjcsXG4gICAgICAgICAgMjIzLFxuICAgICAgICAgIDEwNCxcbiAgICAgICAgICAxOCxcbiAgICAgICAgICA3NFxuICAgICAgICBdXG4gICAgICB9XG4gICAgfSxcbiAgICBcInNpZ25hdHVyZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDEyMixcbiAgICAgICAgMjIyLFxuICAgICAgICAxNjksXG4gICAgICAgIDE3OSxcbiAgICAgICAgMTU5LFxuICAgICAgICAyNyxcbiAgICAgICAgOTgsXG4gICAgICAgIDE4MyxcbiAgICAgICAgMjAsXG4gICAgICAgIDc2LFxuICAgICAgICAyNSxcbiAgICAgICAgMjI3LFxuICAgICAgICAxODIsXG4gICAgICAgIDc0LFxuICAgICAgICAzNSxcbiAgICAgICAgOTQsXG4gICAgICAgIDYzLFxuICAgICAgICAxOTgsXG4gICAgICAgIDQzLFxuICAgICAgICAyMDIsXG4gICAgICAgIDk5LFxuICAgICAgICAxOTMsXG4gICAgICAgIDEwMCxcbiAgICAgICAgMTM5LFxuICAgICAgICAzOSxcbiAgICAgICAgNTYsXG4gICAgICAgIDM2LFxuICAgICAgICAyMDEsXG4gICAgICAgIDExMSxcbiAgICAgICAgMjMzLFxuICAgICAgICAxNzQsXG4gICAgICAgIDQ2LFxuICAgICAgICAyMzQsXG4gICAgICAgIDY1LFxuICAgICAgICAyMTcsXG4gICAgICAgIDE5LFxuICAgICAgICAxMDYsXG4gICAgICAgIDEyMSxcbiAgICAgICAgNzcsXG4gICAgICAgIDE1MCxcbiAgICAgICAgMyxcbiAgICAgICAgMjksXG4gICAgICAgIDIxMixcbiAgICAgICAgMTU2LFxuICAgICAgICAxNTEsXG4gICAgICAgIDIyNyxcbiAgICAgICAgMTkwLFxuICAgICAgICAxNDIsXG4gICAgICAgIDIzOSxcbiAgICAgICAgMjAyLFxuICAgICAgICA0NCxcbiAgICAgICAgNzMsXG4gICAgICAgIDIzMixcbiAgICAgICAgMTY2LFxuICAgICAgICA5OSxcbiAgICAgICAgMTU1LFxuICAgICAgICAxMDAsXG4gICAgICAgIDgsXG4gICAgICAgIDc5LFxuICAgICAgICAzNSxcbiAgICAgICAgMTMzLFxuICAgICAgICAyMzMsXG4gICAgICAgIDExOSxcbiAgICAgICAgNVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJrZXlJZFwiOiAxXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uSWRcIjogMjQyLFxuICBcImFkdlNlY3JldEtleVwiOiBcIkJCT1dnbk5wSEQyYnFPeWJqRDR1Y3BXQVowdlBGU0h3a2djZ0tEd2dPU289XCIsXG4gIFwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzXCI6IFtcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiMjM0NzA1NjAyNTMyMEBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiMjI5OTM4NjU3NEI3MjAxRjRFOTU1NENFMkE0OTAyMzJcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzI4MjMzMDk0XG4gICAgfVxuICBdLFxuICBcIm5leHRQcmVLZXlJZFwiOiAzMSxcbiAgXCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZFwiOiAzMSxcbiAgXCJhY2NvdW50U3luY0NvdW50ZXJcIjogMCxcbiAgXCJhY2NvdW50U2V0dGluZ3NcIjoge1xuICAgIFwidW5hcmNoaXZlQ2hhdHNcIjogZmFsc2VcbiAgfSxcbiAgXCJkZXZpY2VJZFwiOiBcImV6Y1ZYSGNDUjVTdGZ6SE82R3h3c3dcIixcbiAgXCJwaG9uZUlkXCI6IFwiODYwODcxZmItYWY5ZS00NGY5LWI4YTMtODY4NGJjMzBlYjJlXCIsXG4gIFwiaWRlbnRpdHlJZFwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDgxLFxuICAgICAgMjU0LFxuICAgICAgMTYwLFxuICAgICAgMjMwLFxuICAgICAgMTI4LFxuICAgICAgMzUsXG4gICAgICAxNjQsXG4gICAgICAxODQsXG4gICAgICA3NyxcbiAgICAgIDExOSxcbiAgICAgIDM3LFxuICAgICAgMjIyLFxuICAgICAgMjQsXG4gICAgICAyNTMsXG4gICAgICAxNzIsXG4gICAgICAyMjQsXG4gICAgICAyNDYsXG4gICAgICAxOTksXG4gICAgICAxNDcsXG4gICAgICAxMTZcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiB0cnVlLFxuICBcImJhY2t1cFRva2VuXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgNjMsXG4gICAgICAyMDYsXG4gICAgICAxMTYsXG4gICAgICAxNzIsXG4gICAgICA3NyxcbiAgICAgIDg5LFxuICAgICAgMTE0LFxuICAgICAgMTA4LFxuICAgICAgMTU5LFxuICAgICAgMTUyLFxuICAgICAgMjUsXG4gICAgICA2MixcbiAgICAgIDE4NCxcbiAgICAgIDE3MCxcbiAgICAgIDcyLFxuICAgICAgMTcxLFxuICAgICAgNDUsXG4gICAgICA4NyxcbiAgICAgIDE3OCxcbiAgICAgIDEzMFxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25cIjoge30sXG4gIFwicGFpcmluZ0NvZGVcIjogXCJCNUxISDlaWVwiLFxuICBcIm1lXCI6IHtcbiAgICBcImlkXCI6IFwiMjM0NzA1NjAyNTMyMDo5MkBzLndoYXRzYXBwLm5ldFwiLFxuICAgIFwibGlkXCI6IFwiMjQ4NzUxNjcxMjE4MTk1OjkyQGxpZFwiXG4gIH0sXG4gIFwiYWNjb3VudFwiOiB7XG4gICAgXCJkZXRhaWxzXCI6IFwiQ1AyZWxzRUNFSUQ5aXJnR0dBRWdBQ2dBXCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlS2V5XCI6IFwiT041NHBweXkyR3Jxa3hyQldNTVpUQnBKaTZGZU9kUkYrS0t1L0pYTmlFRT1cIixcbiAgICBcImFjY291bnRTaWduYXR1cmVcIjogXCJLbDBxbk52ZC8ydWlwem0vWndBUUVoWm5vbk1mMkhzdGtTWG5WWS9sQ0ZYOVdINXpUS0NMNzh4WUdzR0hVRjQ4TllwY1EyN1NaU2xoSGJaeU9Qd2hBdz09XCIsXG4gICAgXCJkZXZpY2VTaWduYXR1cmVcIjogXCJqMEhYN0Y4NHlqN2JNL3NZZWJhSjRVdEsxbVdpYlF4eURacVNsTUtnYW1XaGF3L0d6OUJuTGE4TlBDdk1zTXNhdm52NFN0RlF3OVlGWFJjcmFLZTRDUT09XCJcbiAgfSxcbiAgXCJzaWduYWxJZGVudGl0aWVzXCI6IFtcbiAgICB7XG4gICAgICBcImlkZW50aWZpZXJcIjoge1xuICAgICAgICBcIm5hbWVcIjogXCIyMzQ3MDU2MDI1MzIwOjkyQHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZGV2aWNlSWRcIjogMFxuICAgICAgfSxcbiAgICAgIFwiaWRlbnRpZmllcktleVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDUsXG4gICAgICAgICAgNTYsXG4gICAgICAgICAgMjIyLFxuICAgICAgICAgIDEyMCxcbiAgICAgICAgICAxNjYsXG4gICAgICAgICAgMTU2LFxuICAgICAgICAgIDE3OCxcbiAgICAgICAgICAyMTYsXG4gICAgICAgICAgMTA2LFxuICAgICAgICAgIDIzNCxcbiAgICAgICAgICAxNDcsXG4gICAgICAgICAgMjYsXG4gICAgICAgICAgMTkzLFxuICAgICAgICAgIDg4LFxuICAgICAgICAgIDE5NSxcbiAgICAgICAgICAyNSxcbiAgICAgICAgICA3NixcbiAgICAgICAgICAyNixcbiAgICAgICAgICA3MyxcbiAgICAgICAgICAxMzksXG4gICAgICAgICAgMTYxLFxuICAgICAgICAgIDk0LFxuICAgICAgICAgIDU3LFxuICAgICAgICAgIDIxMixcbiAgICAgICAgICA2OSxcbiAgICAgICAgICAyNDgsXG4gICAgICAgICAgMTYyLFxuICAgICAgICAgIDE3NCxcbiAgICAgICAgICAyNTIsXG4gICAgICAgICAgMTQ5LFxuICAgICAgICAgIDIwNSxcbiAgICAgICAgICAxMzYsXG4gICAgICAgICAgNjVcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH1cbiAgXSxcbiAgXCJwbGF0Zm9ybVwiOiBcImFuZHJvaWRcIixcbiAgXCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXBcIjogMTcyODIzMzA5MixcbiAgXCJteUFwcFN0YXRlS2V5SWRcIjogXCJBQUFBQUFmZVwiXG59IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBQWZlLmpzb24iOiB7fQp9",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
